In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/ziya07/college-student-health-behavior-dataset/enhanced_student_health_dataset_50k.xls
/kaggle/input/datasets/ziya07/college-student-health-behavior-dataset/student_health_dataset_50k.csv

In [5]:
df=pd.read_csv("/kaggle/input/datasets/ziya07/college-student-health-behavior-dataset/student_health_dataset_50k.csv")
df

,student_id,timestamp,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake,diet_type,stress_level,sleep_quality,physical_activity_level,smoking_alcohol,gender,health_condition
0,1102,2025-01-01 00:00:00,9.29,67.4,28.56,2113.0,5227,91.3,2.08,veg,high,average,active,yes,other,at-risk
1,1435,2025-01-01 01:00:00,9.33,57.2,30.17,2060.0,14460,67.0,2.57,veg,medium,average,active,occasional,male,at-risk
2,1860,2025-01-01 02:00:00,8.33,73.7,19.93,2236.0,14589,52.6,1.93,non-veg,high,average,active,no,other,at-risk
3,1270,2025-01-01 03:00:00,5.60,61.9,22.02,2650.0,12618,55.2,2.97,veg,high,average,active,no,other,unhealthy
4,1106,2025-01-01 04:00:00,9.10,69.6,20.85,1985.0,14518,27.1,3.09,non-veg,medium,poor,sedentary,occasional,male,at-risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1381,2030-09-15 03:00:00,9.88,69.9,23.20,2311.0,7572,83.5,3.47,non-veg,low,average,sedentary,no,female,at-risk
49996,1044,2030-09-15 04:00:00,8.13,63.0,20.16,1819.0,13497,44.2,2.26,non-veg,low,good,sedentary,no,other,at-risk
49997,1916,2030-09-15 05:00:00,6.06,73.1,19.40,1917.0,5868,7.3,2.77,balanced,medium,poor,moderate,occasional,other,at-risk
49998,1171,2030-09-15 06:00:00,5.65,75.6,18.81,2067.0,10206,27.6,3.37,non-veg,low,good,moderate,yes,other,at-risk
49999,1220,2030-09-15 07:00:00,6.98,81.8,16.00,2266.0,3904,49.8,2.06,veg,low,poor,active,occasional,male,at-risk

In [12]:
df.groupby("sleep_quality")["heart_rate"].mean()

sleep_quality
average    75.069704
good       75.022502
poor       74.915954
Name: heart_rate, dtype: float64

In [13]:
df.groupby(["sleep_quality","diet_type"])["heart_rate"].mean()

sleep_quality  diet_type
average        balanced     75.106950
               non-veg      74.856802
               veg          75.245606
good           balanced     75.033345
               non-veg      74.872331
               veg          75.163743
poor           balanced     75.009768
               non-veg      74.929791
               veg          74.807218
Name: heart_rate, dtype: float64

In [21]:
df.groupby(["sleep_quality","diet_type","gender"])["heart_rate"].mean()

sleep_quality  diet_type  gender
average        balanced   female    75.043553
                          male      74.778300
                          other     75.505360
               non-veg    female    74.820789
                          male      74.494614
                          other     75.274139
               veg        female    75.661827
                          male      75.223844
                          other     74.853859
good           balanced   female    74.995824
                          male      75.228441
                          other     74.872737
               non-veg    female    74.774441
                          male      74.852486
                          other     74.989547
               veg        female    75.171694
                          male      75.217929
                          other     75.102627
poor           balanced   female    75.106599
                          male      74.898326
                          other     75.023895
               non-veg    female    74.967110
                          male      75.137468
                          other     74.675715
               veg        female    74.579525
                          male      75.109602
                          other     74.730836
Name: heart_rate, dtype: float64

In [23]:
df.groupby(["sleep_quality","diet_type"])["heart_rate"].agg(["mean","max","median","count"])

                              mean    max  median  count
sleep_quality diet_type
average       balanced   75.106950  116.0    75.1   5626
              non-veg    74.856802  118.3    74.9   5535
              veg        75.245606  110.5    75.2   5508
good          balanced   75.033345  114.2    75.1   5551
              non-veg    74.872331  112.9    74.9   5602
              veg        75.163743  112.0    75.4   5530
poor          balanced   75.009768  120.0    74.9   5549
              non-veg    74.929791  110.2    75.2   5599
              veg        74.807218  110.2    74.9   5500

In [24]:
df.groupby(["sleep_quality","diet_type","gender"])["heart_rate"].agg(
    ag_mean="mean",
    maximum="max",
    middle="median",
    total="count")

                                  ag_mean  maximum  middle  total
sleep_quality diet_type gender
average       balanced  female  75.043553    110.9   74.75   1908
                        male    74.778300    105.1   75.00   1871
                        other   75.505360    116.0   75.40   1847
              non-veg   female  74.820789    118.3   74.80   1775
                        male    74.494614    105.9   74.60   1931
                        other   75.274139    104.9   75.30   1829
              veg       female  75.661827    110.5   75.70   1839
                        male    75.223844    110.5   75.15   1816
                        other   74.853859    108.5   74.70   1853
good          balanced  female  74.995824    108.5   74.80   1868
                        male    75.228441    109.6   75.30   1860
                        other   74.872737    114.2   74.80   1823
              non-veg   female  74.774441    107.9   74.70   1835
                        male    74.852486    112.9   74.90   1911
                        other   74.989547    110.2   75.00   1856
              veg       female  75.171694    110.9   75.50   1830
                        male    75.217929    103.6   75.30   1835
                        other   75.102627    112.0   75.40   1865
poor          balanced  female  75.106599    105.1   75.30   1864
                        male    74.898326    110.0   74.80   1852
                        other   75.023895    120.0   74.70   1833
              non-veg   female  74.967110    104.9   75.40   1803
                        male    75.137468    110.2   75.20   1943
                        other   74.675715    106.1   74.70   1853
              veg       female  74.579525    110.2   74.65   1812
                        male    75.109602    108.4   75.00   1833
                        other   74.730836    108.7   74.90   1855

In [32]:
df.groupby(["gender","diet_type","health_condition"]).agg({
    "water_intake":["mean","max","min","count"],
    "heart_rate":["mean","max"],
    "sleep_duration":"mean",
})

                                  water_intake                   heart_rate  \
                                          mean   max   min count       mean
gender diet_type health_condition
female balanced  at-risk              2.194544  4.84  0.50  4908  75.044804
                 fit                  2.179618  4.12  0.50   288  74.725694
                 unhealthy            2.253243  4.88  0.50   444  75.299775
       non-veg   at-risk              2.198384  4.62  0.50  4776  74.871985
                 fit                  2.194772  3.82  0.50   241  74.956017
                 unhealthy            2.161364  4.10  0.50   396  74.572475
       veg       at-risk              2.200877  4.94  0.50  4754  75.168027
                 fit                  2.211500  4.40  0.62   280  75.135357
                 unhealthy            2.218702  4.16  0.50   447  74.849441
male   balanced  at-risk              2.211671  4.65  0.50  4848  74.971679
                 fit                  2.191908  4.36  0.50   304  74.576316
                 unhealthy            2.170928  4.45  0.50   431  75.203944
       non-veg   at-risk              2.193765  4.51  0.50  5073  74.761285
                 fit                  2.180537  4.36  0.50   298  75.507718
                 unhealthy            2.206836  4.65  0.50   414  75.166667
       veg       at-risk              2.211767  4.91  0.50  4806  75.181190
                 fit                  2.249401  4.10  0.50   284  74.147535
                 unhealthy            2.281269  4.21  0.50   394  75.960914
other  balanced  at-risk              2.185667  4.68  0.50  4757  75.113160
                 fit                  2.184362  3.90  0.50   282  75.523050
                 unhealthy            2.186897  4.44  0.50   464  75.128017
       non-veg   at-risk              2.183703  4.83  0.50  4882  74.963990
                 fit                  2.212070  4.16  0.58   227  74.346696
                 unhealthy            2.127949  4.35  0.50   429  75.478322
       veg       at-risk              2.196827  4.60  0.50  4914  74.909198
                 fit                  2.193855  3.95  0.50   262  74.227099
                 unhealthy            2.215340  4.29  0.50   397  75.176322

                                         sleep_duration
                                     max           mean
gender diet_type health_condition
female balanced  at-risk           110.9       7.062848
                 fit               100.4       8.153750
                 unhealthy          99.5       5.116306
       non-veg   at-risk           118.3       7.087617
                 fit                97.5       8.130249
                 unhealthy          98.7       5.067702
       veg       at-risk           110.9       7.102053
                 fit               106.9       8.233143
                 unhealthy          96.2       5.141678
male   balanced  at-risk           110.0       7.098214
                 fit               102.4       8.220362
                 unhealthy         102.6       5.182297
       non-veg   at-risk           112.9       7.077400
                 fit               102.5       8.083221
                 unhealthy         103.2       5.130821
       veg       at-risk           110.5       7.108481
                 fit                98.2       8.059401
                 unhealthy         107.3       5.115152
other  balanced  at-risk           116.0       7.075552
                 fit               107.4       8.194574
                 unhealthy         120.0       5.116207
       non-veg   at-risk           110.2       7.108177
                 fit                97.3       8.267885
                 unhealthy         103.9       5.106131
       veg       at-risk           112.0       7.119650
                 fit               101.0       8.235496
                 unhealthy         103.2       5.104282

In [41]:
summary=df.groupby(["diet_type","sleep_quality"]).agg({
    "water_intake":["mean","max","min"],
    "heart_rate":["mean"],
    "sleep_duration":"mean"
})
largest=summary.nlargest(2,("water_intake","mean"))
largest

                        water_intake            heart_rate sleep_duration
                                mean   max  min       mean           mean
diet_type sleep_quality
veg       average           2.213789  4.94  0.5  75.245606       6.993431
          poor              2.211451  4.91  0.5  74.807218       7.035025